### PR TITLE
Implemented query filter

### PR DESCRIPTION
**Pull request by tibormohr**
Implemented query filter

### CODE REVIEW

**Comment by tibormohr** [comment]
Hi @valdisiljuconoks, Could you check the PR?

**Review by valdisiljuconoks — APPROVED** [review]

**Comment by valdisiljuconoks** [comment]
Moved default values form library to "client app" -> so that users of the library will be able to control whether feature is enabled or not and set the page size.

**Comment by valdisiljuconoks** [comment]
@tibormohr got some compilation errors, fixed those.
But seems like you forgot to commit to aspnet repo.

Could you just drop `LocalizationResourcesController.cs` file (maybe something more you have pending check-in) - so I can complete the feature and release it.

Thx! 👍

**Comment by tibormohr** [comment]
Hi, 

Sorry, it was my mistake it was not correctly attached the submodule.

I just created a PR for aspnet repo.

Thanks ahead
/TM

**Pull request merged**
